services:
  - type: web
    name: fastfood-project
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://fastfood-project.onrender.com
